# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Retested IT
tagline:             Thoughts on quality management
url:                 http://retested.it
paginate:            1
baseurl:             ""

# Navigation links
pages_list:
  About: '/about'
  Posts: '/posts'
  Feed: '/atom.xml'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Pawel Uramowski
  url:               https://twitter.com/paweluramowski
  email:             pawel.uramowski@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/paweluramowski/retested
